<div id="tasksList" class="tasks-container jsTaskList">
    <div class="bar-top jsBarTop">
        <div class="title"><?= $this->listActive->title; ?></div>
        <div class="buttons jsButtons">
            <div class="button minimize jsButton" data-action="minimize"></div>
            <div class="button maximize jsButton" data-action="maximize"></div>
            <div class="button close jsButton" data-action="close"></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="list jsList">
        <? if ($this->listActive) : ?>
            <? $tasks = $this->listActive->getTasks(); ?>
            <? if ($tasks->count() > 0) : ?>
                <table class="tasks-table">
                <? foreach ($tasks as $task) : ?>
                    <?= $this->partial('_templates/html/task.phtml', array('task' => $task)); ?>
                <? endforeach; ?>
                </table>
            <? else : ?>
                <div class="empty-placeholder">
                    <span class="text">Пока нет ни одной задачи.</span>
                </div>
            <? endif; ?>
        <? endif; ?>
    </div>
    <div class="bar-bottom jsBarBottom">
        <div class="buttons">
            <div class="button add jsButton" data-action="addTask"></div>
            <div class="button delete jsButton" data-action="deleteTask"></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>