<div id="tasksList" class="tasks-container jsTaskList">
    <div class="bar-top jsBarTop">
        <div class="title"><?= $this->listActive->title; ?></div>
        <div class="buttons jsButtons">
            <div class="button minimize jsButton" data-action="minimize"></div>
            <div class="button maximize jsButton" data-action="maximize"></div>
            <div class="button close jsButton" data-action="close"></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="list jsList" data-id="<?= $this->listActive->id; ?>">
        <? $tasks = $this->listActive->getTasks(); ?>
        <? if ($tasks->count() > 0) : ?>
            <table class="tasks-table">
            <? foreach ($tasks as $task) : ?>
                <?= $this->partial('_templates/html/task.phtml', array('task' => $task)); ?>
            <? endforeach; ?>
            </table>
        <? endif; ?>
    </div>
    <div class="bar-bottom jsBarBottom">
        <div class="buttons">
            <div class="button add jsButton" data-action="addTask"></div>
            <div class="button delete jsButton" data-action="deleteTask"></div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>

<?= $this->partial('_templates/ejs/list-empty.ejs'); ?>
<?= $this->partial('_templates/ejs/task.ejs'); ?>