<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <base href="http://<?=$_SERVER['HTTP_HOST'];?>/"/>
    <?php $this->initCss(); ?>
    <?php $this->initJs(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
<!-- container -->
<div id="container" class="inner-container">
    <?= $this->layout()->content; ?>
</div>
<!-- /container -->
</body>
</html>
